---
# tasks file for java
- name: apt update
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu" 
- name: install epel-release
  ansible.builtin.yum:
    name: epel-release
    state: present    
  when: ansible_facts['distribution'] == "CentOS"   
- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present    
- name: install npm
  ansible.builtin.package:
    name: npm
    state: present      